# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Untaint
version:      1.00
version_from: lib/Class/DBI/Untaint.pm
installdirs:  site
requires:
    CGI::Untaint:                  1
    Class::DBI:                    0.95
    Test::More:                    0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
